config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "home#index"
    devise_for :accounts, controllers: {
      sessions: "accounts/sessions",
      registrations: "accounts/registrations",
      confirmations: "accounts/confirmations"
    }
    resources :accounts, only: %i(show edit update)

    resources :books, only: %i(index show), path: "library" do
      resources :book_comments, path: "comments"
    end
    resources :authors, only: %i(show)

    resource :carts, only: %i(show destroy)
    resources :borrow_items, only: %i(create destroy)
    resources :borrow_infos, only: %i(index show new create) do
      member do
        get "download", to: "borrow_infos#download"
        get "preview", to: "borrow_infos#preview"
        post "status_action", to: "borrow_infos#handle_status_action"
        patch "status_action", to: "borrow_infos#handle_status_action"
      end
    end

    resources :author_followers, only: %i(create destroy)

    resources :notifications, only: %i(index update) do
      collection do
        post "read_all", to: "notifications#read_all"
      end
    end
  end

  namespace :admin do
    scope "(:locale)", locale: /en|vi/ do
      root "home#index"
      get "export/library", to: "home#export_library"

      authenticate :admin_account do
        mount Sidekiq::Web => "/jobs"
      end

      devise_for :accounts, path: "", controllers: {
        sessions: "admin/sessions"
      }, skip: [:registrations]

      resources :authors, :genres, :publishers
      resources :books do
        member do
          get :amend, to: "books#amend_edit"
          patch :amend
        end
      end
      resources :users, only: %i(index show) do
        member do
          post :active, :inactive
        end
      end
      resources :borrows, only: %i(index show) do
        member do
          post :approve, :reject, :return, :remind
        end
        collection do
          get ":group", to: "borrows#index", as: "",
                        constraints: {group: /pending|history|borrowing/},
                        defaults: {group: :borrowing}
        end
      end
      resources :notifications, only: %i(index update) do
        collection do
          post "read_all", to: "notifications#read_all"
        end
      end
    end
  end

  namespace :api do
    scope "(:locale)", locale: /en|vi/ do
      namespace :v1 do
        post "authenticate", to: "sessions#authenticate"
        get "me", to: "sessions#me"

        post "register", to: "registrations#register"
        resources :books, only: %i(index show), path: "library" do
          resources :book_comments, only: %i(create update destroy), path: "comments"
        end

        namespace :admin do
          resources :books, only: %i(index create update show destroy) do
            member do
              patch :amend
            end
          end
        end
      end
    end
  end
end

app/models/borrow_info.rb
class BorrowInfo < ApplicationRecord
  enum :status, %i(pending approved rejected canceled returned renewing)

  belongs_to :account
  has_one :response, class_name: BorrowResponse.name,
                     dependent: :destroy
  has_many :borrowings, class_name: BorrowItem.name,
                        dependent: :destroy
  has_many :books, through: :borrowings

  validates :start_at, :end_at, :status, :turns, presence: true
  validate :start_at_validation, :end_at_validation, on: :create
  validates :renewal_at, presence: true, if: ->(borrow){borrow.renewing?}
  validate :renewal_at_validation, on: :update
  validates :turns, numericality: {less_than_or_equal_to: Settings.digit_5.to_i}

  scope :due_first, ->{order(end_at: :desc)}
  scope :includes_user, lambda {\
    includes(account: [{avatar_attachment: [:blob]}, user_info: []])
  }
  scope :includes_response, ->{includes(:response)}
  scope :bquery, lambda {|q|
    references(:account, :user_info)
      .where("accounts.username LIKE ?", "%#{q}%")
      .or(Account.where("accounts.email LIKE ?", "%#{q}%"))
      .or(UserInfo.where("user_infos.name LIKE ?", "%#{q}%"))
  }
  scope :history, ->{where.not(done_at: nil)}
  scope :waiting, ->{pending.or(BorrowInfo.renewing)}
  scope :borrowing, ->{approved.or(BorrowInfo.rejected.where(done_at: nil))}
  scope :for_account, ->(account_id){where(account_id:)}
  scope :desc_order, ->{order(updated_at: :desc)}
  scope :group_status, ->(status){where(status:) if status != "all"}

  def start_at_validation
    return if start_at && start_at >= Date.current

    errors.add(:start_at, I18n.t("date_greater_than_today"))
  end

  def end_at_validation
    if start_at && end_at && end_at > start_at + Settings.digit_10
      errors.add(:end_at, I18n.t("date_maximum_10_days"))
    elsif start_at && end_at && end_at <= start_at
      errors.add(:end_at, I18n.t("return_date_greater_than_borrow_date"))
    end
  end

  def renewal_at_validation
    if renewal_at && renewal_at <= end_at
      errors.add(:renewal_at, I18n.t("renewal_date_greater_than_return_date"))
    elsif renewal_at && renewal_at > end_at + Settings.digit_10
      errors.add(:renewal_at, I18n.t("renewal_date_maximum_10_days"))
    end
  end

  def borrowing?
    approved? || (rejected? && !finished?)
  end

  def finished?
    done_at.present?
  end

  def overdue?
    (done_at || Time.zone.today) > end_at
  end

  def out_of_turns?
    turns >= Settings.max_renewals
  end

  def out_of_renew_date?
    Time.zone.today > end_at
  end

  def return_exceed
    final = done_at&.to_date || Time.zone.today
    (final - end_at.to_date).to_i
  end

  def penalty
    overdue? ? I18n.t("penalty_per_overdue") * return_exceed : 0
  end

  def perform_action action, *args
    transaction do
      send action, *args
    end
  rescue ActiveRecord::RecordInvalid
    reload
    false
  end

  def self.ransackable_attributes _auth_object = nil
    %w(status id start_at end_at turns)
  end

  private

  def add_to_book_borrowed_count value
    transaction do
      update_books = books.map do |b|
        raise ActiveRecord::Rollback unless b.is_active

        [b.id, {
          id: b.id,
          borrowed_count: b.borrowed_count + value
        }]
      end.to_h
      Book.update! update_books.keys, update_books.values
    end
  end

  def approve
    return unless %w(pending renewing).include? status

    if renewing?
      self.end_at = renewal_at
      self.renewal_at = nil
      self.turns += 1
    else
      return unless add_to_book_borrowed_count(1)
    end
    self.status = :approved
    save!
  end

  def reject
    return unless %w(pending renewing).include? status

    self.done_at = Time.zone.today if pending?
    self.renewal_at = nil
    self.status = :rejected
    save!
  end

  def return
    return unless %w(approved rejected).include? status
    return if done_at

    self.done_at = Time.zone.now
    return unless add_to_book_borrowed_count(-1)

    self.status = :returned
    save!
  end

  def renew end_date
    return unless %w(approved).include? status

    self.status = :renewing
    self.renewal_at = end_date
    save!
  end

  def cancel
    return unless %w(pending renewing).include? status

    if pending?
      self.status = :canceled
      self.done_at = Time.zone.now
    else
      self.renewal_at = nil
      self.status = :approved
    end
    save!
  end
end

app/controllers/borrow_infos_controller.rb
class BorrowInfosController < ApplicationController
  include CartActions

  before_action :authenticate_account!
  before_action :set_cart, only: %i(new)
  before_action :check_cart_empty, only: %i(new)
  before_action :check_user_info, except: %i(index show)
  before_action :set_borrow_info, except: %i(index new create)
  before_action :correct_account, except: %i(index new create)

  def index
    @q = BorrowInfo.ransack(params[:q])
    @pagy, @borrow_infos_sort = pagy(
      @q.result.for_account(current_account).desc_order,
      items: Settings.digit_5
    )
  end

  def show; end

  def new
    @borrow_info = BorrowInfo.new
  end

  def create
    @borrow_info = BorrowInfo.new borrow_info_params
    @borrow_info.account_id = current_account.id if account_signed_in?

    if @borrow_info.save
      move_item_from_cart
      flash[:success] = t "borrow_info_success"
      redirect_to @borrow_info
    else
      render :new, status: :bad_request
    end
  end

  def handle_status_action
    status = params[:status] if params[:status].present?

    case status
    when "pending"
      cancel_borrow_request
    when "approved"
      update_return_date
    when "renewing"
      cancel_borrow_request
    else
      flash[:danger] = t "unknown_status_request"
    end
  end

  def download
    send_pdf(disposition: "attachment")
  end

  def preview
    send_pdf(disposition: "inline")
  end

  private

  def set_borrow_info
    @borrow_info = BorrowInfo.find_by(id: params[:id])
    return if @borrow_info

    flash[:warning] = t "borrow_info_not_found"
    redirect_to borrow_infos_path
  end

  def borrow_info_params
    params
      .require(:borrow_info)
      .permit :start_at, :end_at, :status, :turns, :account_id, :renewal_at
  end

  def move_item_from_cart
    @current_cart.borrowings.include_books.each do |borrow_item|
      @borrow_info.borrowings << borrow_item
      borrow_item.update(cart_id: nil)
    end

    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
  end

  def cancel_borrow_request
    if @borrow_info.perform_action :cancel
      flash.now[:success] = t "cancel_request_successfully"
      redirect_to @borrow_info
    else
      flash[:danger] = t "cancel_request_failed"
      redirect_to borrow_infos_path
    end
  end

  def update_return_date
    if @borrow_info.perform_action :renew, borrow_info_params[:renewal_at]
      flash.now[:success] = t "renew_request_successfully"
      redirect_to @borrow_info
    else
      render :show, status: :bad_request
    end
  end

  def correct_account
    return if @borrow_info && @borrow_info.account == current_account

    flash.now[:warning] = t "borrow_info_not_found"
    redirect_to borrow_infos_path
  end

  def send_pdf disposition:
    pdf = BorrowInfoPdf.new(@borrow_info)
    send_data(
      pdf.render,
      filename: t("pdf_filename") + "#{@borrow_info.id}.pdf",
      type: "application/pdf",
      disposition:
    )
  end
end

app/helpers/borrow_infos_helper.rb
module BorrowInfosHelper
  def set_class_based_on status
    case status
    when "pending" then "info"
    when "approved" then "success"
    when "renewing" then "purple"
    when "rejected" then "danger"
    when "canceled" then "dark"
    when "returned" then "warning"
    else ""
    end
  end

  def show_actions status
    case status
    when "pending" then cancel_btn
    when "approved" then renewals_form
    when "renewing" then cancel_btn
    when "rejected" then rejected_content
    when "canceled" then canceled_content
    when "returned" then returned_content
    else ""
    end
  end

  def cancel_btn
    link_to t("cancel_borrow_request"),
            status_action_borrow_info_path(
              id: @borrow_info.id,
              status: @borrow_info.status
            ),
            data: {turbo_method: :post, turbo_confirm: t("you_sure?")},
            class: "btn btn-outline-danger"
  end

  def renewals_form
    return if @borrow_info.out_of_turns?
    return if @borrow_info.out_of_renew_date?

    form_with(model: @borrow_info,
              url: status_action_borrow_info_path(id: @borrow_info.id,
                                                  status: @borrow_info.status),
              data: {turbo_method: :patch, turbo_confirm: t("you_sure?")},
              class: "d-flex align-items-center my-4") do |form|
      concat(form.label(
               :renewal_at, t("borrow_renewals_date"), class: "fw-semibold"
             ))
      concat(content_tag(:span, "(#{t('if_want')}):",
                         class: "ms-1 text-secondary"))
      concat(form.date_field(:renewal_at, class: "form-control w-auto mx-3",
                             min: Date.current))
      concat(form.submit(t("renewals"), class: "btn btn-primary"))
    end
  end

  def rejected_content
    content_tag(:div, class: "alert alert-danger") do
      concat(content_tag(:span,
                         "#{t('reject_reason')}: ",
                         class: "fw-semibold"))
      concat(content_tag(:span,
                         @borrow_info.response.content,
                         class: "text-break"))
    end
  end

  def canceled_content
    content_tag(:div, class: "alert alert-dark") do
      concat(content_tag(:span, "#{t('canceled_date')}: ",
                         class: "fw-semibold"))
      concat(content_tag(:span, @borrow_info.done_at.to_date))
    end
  end

  def returned_content
    content_tag(:div) do
      concat(content_tag(:div, class: "alert alert-warning") do
               concat(content_tag(:span, "#{t('actual_return_date')}: ",
                                  class: "fw-semibold"))
               concat(content_tag(:span, @borrow_info.done_at.to_date))
             end)
      concat(penalty_content) if @borrow_info.overdue?
    end
  end

  def penalty_content
    content_tag(:div, class: "alert alert-danger fw-bold") do
      concat(content_tag(:span, "#{t('penalty')}: "))
      concat(content_tag(:span, number_to_currency(@borrow_info.penalty)))
      concat(content_tag(:span, " (#{t('exceed')}: "))
      concat(content_tag(:span, "#{@borrow_info.return_exceed})"))
    end
  end

  def show_borrow_status_header
    return " - #{t('all')}" if @q.status_eq.blank?

    " - #{t(BorrowInfo.statuses.keys[@q.status_eq].to_s)}"
  end

  def status_options
    BorrowInfo.statuses.map{|key, value| [t(key), value]}
  end
end

app/views/borrow_infos/_pdf_btns.html.erb
<%= link_to t(".preview_pdf"), preview_borrow_info_path, target: "_blank", class: "btn btn-light ms-2" %>
<%= link_to t(".download_pdf"), download_borrow_info_path, class: "btn btn-light ms-2" %>

app/views/borrow_infos/index.html.erb
<% provide(:title, t("borrow_history")) %>
<div class="mb-5">
  <% breadcrumb :borrow_infos, @borrow_infos %>
  <h1><%= t "borrow_history" %></h1>
  <%= search_form_for @q, class: "d-flex justify-content-between align-items-center mt-5 mb-2" do |f| %>
    <div>
      <h3 class="text-secondary"><%= t "status" %><%= show_borrow_status_header %></h3>
    </div>
    <div class="d-flex">
      <%=
        f.select :status_eq,
        options_for_select(status_options, selected: @q.status_eq),
        { include_blank: t("all") },
        { class: "form-select" }
      %>
      <%= f.submit t("filter"), class: "btn btn-primary ms-2" %>
    </div>
  <% end %>
  <% if @borrow_infos_sort.any? %>
    <div class="d-flex justify-content-center mb-4">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th scope="col"><%= sort_link(@q, :id, t("borrow_id")) %></th>
          <th scope="col"><%= sort_link(@q, :start_at, t("activerecord.attributes.borrow_info.borrow_date")) %></th>
          <th scope="col"><%= sort_link(@q, :end_at, t("activerecord.attributes.borrow_info.return_date")) %></th>
          <th scope="col"><%= sort_link(@q, :turns, t("activerecord.attributes.borrow_info.turns")) %></th>
          <th scope="col"><%= t "status" %></th>
          <th scope="col"><%= t "action" %></th>
        </tr>
      </thead>
      <tbody>
        <% @borrow_infos_sort.each do |borrow_info| %>
          <tr>
            <th scope="row"><%= borrow_info.id %></th>
            <td><%= borrow_info.start_at %></td>
            <td>
              <%= borrow_info.renewing? ? borrow_info.renewal_at : borrow_info.end_at %>
              <% if borrow_info.borrowing? %>
                <% days_left = (borrow_info.end_at - Date.current).to_i %>
                <span class="fw-bold text-danger">
                  (<% if days_left >= 0 %>
                    <%= "#{days_left} #{t('days_left', count: days_left)}" %>
                  <% else %>
                    <%= "#{t("penalty")} #{number_to_currency(borrow_info.penalty)}" %>
                  <% end %>)
                </span>
              <% end %>
            </td>
            <td><%= borrow_info.turns %></td>
            <td class="text-<%= set_class_based_on(borrow_info.status) %>"><%= t "#{borrow_info.status}" %></td>
            <td><%= link_to t("details"), borrow_info_path(borrow_info) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <%= render "shared/not_found_content", text: t("no_borrow_info") %>
  <% end %>
</div>

app/views/borrow_infos/new.html.erb
<% provide :title, t(".borrow_info_create") %>

<h1><%= t ".borrow_info_create" %></h1>
<div class="my-4">
  <%= form_with model: @borrow_info, data: {turbo_method: :post, turbo_confirm: t("you_sure?")} do |form| %>
    <div class="row">
      <div class="col-md-6 row">
        <% @current_cart.borrowings.include_books.each do |borrow_item| %>
          <% book = borrow_item.book %>
          <div class="col-md-6 mb-3">
            <%= render "shared/book_card", book: book %>
          </div>
        <% end %>
      </div>
      <div class="col-md-6">
        <div class="mb-3">
          <%= form.label :borrow_date, class: "form-label required fw-semibold" %>
          <%= form.date_field :start_at, class: "form-control", min: Date.current, id: "start-at" %>
          <%= render "shared/error_messages", resource: @borrow_info, field: :start_at %>
        </div>
        <div class="mb-3">
          <%= form.label :return_date, class: "form-label required fw-semibold" %>
          <%= form.date_field :end_at, class: "form-control", min: Date.current, id: "end-at" %>
          <%= render "shared/error_messages", resource: @borrow_info, field: :end_at %>
        </div>
        <div class="mb-3">
          <p class="form-label fw-semibold"><%= t "borrow_infos.borrow_renewals" %>: <span class="fw-normal">5</span></p>
        </div>
        <div class="row mb-3">
          <%= form.submit t(".borrow_info_create"), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/borrow_infos/show.html.erb
<% provide :title, t(".borrow_info") %>
<div>
  <% breadcrumb :borrow_info, @borrow_info %>
  <div class="d-flex align-items-center mb-4">
    <h1 class="m-0 me-2"><%= t ".borrow_info" %> #<%= @borrow_info.id %></h1>
    <% if @borrow_info.status == "approved" %>
      <%= render "pdf_btns" %>
    <% end %>
  </div>
  <p><span class="fw-semibold"><%= t "borrow_infos.borrow_date" %>: </span><%= @borrow_info.start_at %></p>
  <p>
    <span class="fw-semibold"><%= t "borrow_infos.return_date" %>: </span>
    <%= @borrow_info.renewing? ? @borrow_info.renewal_at : @borrow_info.end_at %>
    <% if @borrow_info.borrowing? %>
      <% days_left = (@borrow_info.end_at - Date.current).to_i %>
      <span class="fw-bold text-danger">
        (<% if days_left >= 0 %>
          <%= "#{days_left} #{t('days_left', count: days_left)}" %>
        <% else %>
          <%= "#{t("penalty")} #{number_to_currency(@borrow_info.penalty)}" %>
        <% end %>)
      </span>
    <% end %>
  </p>
  <p>
    <span class="fw-semibold"><%= t "activerecord.attributes.borrow_info.turns" %>: </span><%= @borrow_info.turns %>
    <span class="text-secondary"><%= t(".turns_left", turns_count: Settings.max_renewals - @borrow_info.turns) %></span>
  </p>
  <p><span class="fw-semibold"><%= t "status" %>: </span><span class="fs-6 badge text-bg-<%= set_class_based_on(@borrow_info.status) %>"><%= t("#{@borrow_info.status}") %></span></p>
  <%= show_actions @borrow_info.status %>
  <%= render "shared/error_messages", resource: @borrow_info, field: :renewal_at %>
</div>
<div class="mt-4">
  <h2 class="border-bottom"><%= t ".borrow_book_list" %> - <%= @borrow_info.borrowings.sum(&:quantity) %> <%= t "book" %></h2>
  <div class="mt-1 mb-5 row row-cols-1 row-cols-md-5 g-4">
    <% @borrow_info.borrowings.include_books.each do |borrow_item| %>
      <% book = borrow_item.book %>
      <div class="col">
        <%= render "shared/book_card", book: book %>
      </div>
    <% end %>
  </div>
</div>