config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "home#index"
    devise_for :accounts, controllers: {
      sessions: "accounts/sessions",
      registrations: "accounts/registrations",
      confirmations: "accounts/confirmations"
    }
    resources :accounts, only: %i(show edit update)

    resources :books, only: %i(index show), path: "library" do
      resources :book_comments, path: "comments"
    end
    resources :authors, only: %i(show)

    resource :carts, only: %i(show destroy)
    resources :borrow_items, only: %i(create destroy)
    resources :borrow_infos, only: %i(index show new create) do
      member do
        get "download", to: "borrow_infos#download"
        get "preview", to: "borrow_infos#preview"
        post "status_action", to: "borrow_infos#handle_status_action"
        patch "status_action", to: "borrow_infos#handle_status_action"
      end
    end

    resources :author_followers, only: %i(create destroy)

    resources :notifications, only: %i(index update) do
      collection do
        post "read_all", to: "notifications#read_all"
      end
    end
  end

  namespace :admin do
    scope "(:locale)", locale: /en|vi/ do
      root "home#index"
      get "export/library", to: "home#export_library"

      authenticate :admin_account do
        mount Sidekiq::Web => "/jobs"
      end

      devise_for :accounts, path: "", controllers: {
        sessions: "admin/sessions"
      }, skip: [:registrations]

      resources :authors, :genres, :publishers
      resources :books do
        member do
          get :amend, to: "books#amend_edit"
          patch :amend
        end
      end
      resources :users, only: %i(index show) do
        member do
          post :active, :inactive
        end
      end
      resources :borrows, only: %i(index show) do
        member do
          post :approve, :reject, :return, :remind
        end
        collection do
          get ":group", to: "borrows#index", as: "",
                        constraints: {group: /pending|history|borrowing/},
                        defaults: {group: :borrowing}
        end
      end
      resources :notifications, only: %i(index update) do
        collection do
          post "read_all", to: "notifications#read_all"
        end
      end
    end
  end

  namespace :api do
    scope "(:locale)", locale: /en|vi/ do
      namespace :v1 do
        post "authenticate", to: "sessions#authenticate"
        get "me", to: "sessions#me"

        post "register", to: "registrations#register"
        resources :books, only: %i(index show), path: "library" do
          resources :book_comments, only: %i(create update destroy), path: "comments"
        end

        namespace :admin do
          resources :books, only: %i(index create update show destroy) do
            member do
              patch :amend
            end
          end
        end
      end
    end
  end
end

app/views/shared/_book_card.html.erb
<div class="card h-100">
  <%= link_to book_path(book) do %>
    <%= image_tag book.image, class: "card-img-top" if book.image.attached? %>
  <% end %>
  <div class="card-body text-center">
    <h5 class="card-title fw-semibold"><%= book.title %></h5>
    <% if book.authors.any? %>
      <p class="card-text text-secondary"><%= book.authors.map(&:name).join(", ") %></p>
    <% else %>
      <p class="card-text text-secondary"><%= t ".no_authors_found" %></p>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<div class="text-danger mt-2">
  <%= resource.errors.full_messages_for(field).first if resource.errors.any? && resource.errors.include?(field)  %>
</div>

app/views/shared/_not_found_content.html.erb
<div class="alert alert-info text-center mt-4">
  <%= text %>
</div>

app/views/shared/_toastr.html.erb
<script defer>
  <% flash.each do |message_type, message| %>
    <% type = type_for_toastr(message_type) %>
    toastr.<%= type %>('<%= message %>')
  <% end %>
</script>