config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "home#index"
    devise_for :accounts, controllers: {
      sessions: "accounts/sessions",
      registrations: "accounts/registrations",
      confirmations: "accounts/confirmations"
    }
    resources :accounts, only: %i(show edit update)

    resources :books, only: %i(index show), path: "library" do
      resources :book_comments, path: "comments"
    end
    resources :authors, only: %i(show)

    resource :carts, only: %i(show destroy)
    resources :borrow_items, only: %i(create destroy)
    resources :borrow_infos, only: %i(index show new create) do
      member do
        get "download", to: "borrow_infos#download"
        get "preview", to: "borrow_infos#preview"
        post "status_action", to: "borrow_infos#handle_status_action"
        patch "status_action", to: "borrow_infos#handle_status_action"
      end
    end

    resources :author_followers, only: %i(create destroy)

    resources :notifications, only: %i(index update) do
      collection do
        post "read_all", to: "notifications#read_all"
      end
    end
  end

  namespace :admin do
    scope "(:locale)", locale: /en|vi/ do
      root "home#index"
      get "export/library", to: "home#export_library"

      authenticate :admin_account do
        mount Sidekiq::Web => "/jobs"
      end

      devise_for :accounts, path: "", controllers: {
        sessions: "admin/sessions"
      }, skip: [:registrations]

      resources :authors, :genres, :publishers
      resources :books do
        member do
          get :amend, to: "books#amend_edit"
          patch :amend
        end
      end
      resources :users, only: %i(index show) do
        member do
          post :active, :inactive
        end
      end
      resources :borrows, only: %i(index show) do
        member do
          post :approve, :reject, :return, :remind
        end
        collection do
          get ":group", to: "borrows#index", as: "",
                        constraints: {group: /pending|history|borrowing/},
                        defaults: {group: :borrowing}
        end
      end
      resources :notifications, only: %i(index update) do
        collection do
          post "read_all", to: "notifications#read_all"
        end
      end
    end
  end

  namespace :api do
    scope "(:locale)", locale: /en|vi/ do
      namespace :v1 do
        post "authenticate", to: "sessions#authenticate"
        get "me", to: "sessions#me"

        post "register", to: "registrations#register"
        resources :books, only: %i(index show), path: "library" do
          resources :book_comments, only: %i(create update destroy), path: "comments"
        end

        namespace :admin do
          resources :books, only: %i(index create update show destroy) do
            member do
              patch :amend
            end
          end
        end
      end
    end
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController
  def index
    @period = params[:period]&.to_sym || :month
  end

  def export_library
    respond_to do |format|
      format.xlsx do
        @books = Book.includes_info
        @publishers = Publisher.all
        @authors = Author.with_attached_avatar
        @genres = Genre.all
        render xlsx: "books", template: "admin/home/export_library"
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return if current_account.blank?

    @books = {
      books_with_same_genre: current_account.books_with_same_genre,
      books_from_favorite_authors: current_account.books_from_favorite_authors,
      top_rated_books: fetch_books(:top_rated_books),
      most_borrowed_books: fetch_books(:most_borrowed_books)
    }
  end

  private

  def fetch_books scope
    Book.with_image_and_authors.public_send(scope)
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
  def populate_key_by raw, *attributes, &block
    collection = block.call.where(id: raw.keys)
                      .index_by(&:id)
                      .values_at(*raw.keys)
    collection = collection.pluck(*attributes) unless attributes.empty?
    collection.zip raw.values
  end

  def format_period_key raw, type
    keys = raw.keys
    case type
    when :week
      keys = keys.map{|week| "#{t('datetime.week')} #{week}"}
    when :quarter
      keys = keys.map do |year, quarter|
        "#{t('datetime.quarter')} #{quarter}/#{year}"
      end
    end
    keys.zip raw.values
  end

  def trending_book period: :month, limit: Settings.n_trending_items
    BorrowItem.group(:book_id)
              .recently(period)
              .order("count_id desc")
              .limit(limit)
              .count(:id)
  end

  def trending_book_all_time
    week = trending_book(period: :week)
    week = week.transform_values do |v|
      {week: v} if v > 1
    end
    month = trending_book(period: :month)
    month = month.transform_values do |v|
      {month: v} if v > 1
    end
    year = trending_book(period: :year)
    year = year.transform_values do |v|
      {year: v} if v > 1
    end
    raw = week.deep_merge(month).deep_merge(year).compact
    populate_key_by(raw){Book.with_attached_image}
  end

  def stat_book_genre limit = Settings.n_pie_items
    raw = BookGenre.group(:genre_id)
                   .order("count_id desc")
                   .limit(limit)
                   .count(:id)
    populate_key_by(raw, :name){Genre}
  end

  def stat_book_author limit = Settings.n_pie_items
    raw = BookAuthor.group(:author_id)
                    .order("count_id desc")
                    .limit(limit)
                    .count(:id)
    populate_key_by(raw, :name){Author}
  end

  def stat_book_publisher limit = Settings.n_pie_items
    raw = Book.group(:publisher_id)
              .order("count_id desc")
              .limit(limit)
              .count(:id)
    populate_key_by(raw, :name){Publisher}
  end

  def group_by_period collection, period: :month
    group_by_map = {
      week: :date,
      month: :date,
      year: :week,
      all: :quarter
    }
    group = group_by_map[period]
    raw = collection.recently period
    raw = raw.period_group :year if period == :all
    raw = raw.period_group group
    raw = raw.count
    format_period_key raw, group
  end

  def stat_borrow_date period: :month
    group_by_period BorrowInfo, period:
  end

  def stat_borrow_genre limit = Settings.n_pie_items, period: :month
    join_clause = "book_genres ON borrow_items.book_id = book_genres.book_id"
    raw = BorrowItem.recently(period)
                    .joins("INNER JOIN #{join_clause}")
                    .group(:genre_id)
                    .order("count_borrow_items_id DESC")
                    .limit(limit)
                    .count("borrow_items.id")
    populate_key_by(raw, :name){Genre}
  end
end

app/views/home/_author_list.html.erb
<h2 class="fw-semibold"><%= t "authors_following" %></h2>
<hr>
<div class="row row-cols-1 row-cols-md-4 g-4">
  <% @authors.each do |author| %>
    <div class="col text-center">
      <%= link_to author_path(author), class: "text-decoration-none text-reset" do %>
        <%= avatar_for(author, 100) %>
        <p class="mt-2"><%= author.name %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/home/_books_carousel.html.erb
<div class="mb-5">
  <h2 class="fw-semibold mb-4"><%= title %></h2>
  <div class="container text-center my-3">
    <div class="row mx-auto my-auto justify-content-center">
      <div id="recipeCarousel_<%= books.object_id %>" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner" role="listbox">
          <% books.each_with_index do |book, index| %>
            <div class="carousel-item <%= "active" if index.zero? %>">
              <div class="col-md-3">
                <div class="mx-4 h-100"><%= render "shared/book_card", book: book %></div>
              </div>
            </div>
          <% end %>
        </div>
        <a class="carousel-control-prev bg-transparent w-aut" href="#recipeCarousel_<%= books.object_id %>" role="button" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        </a>
        <a class="carousel-control-next bg-transparent w-aut" href="#recipeCarousel_<%= books.object_id %>" role="button" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% provide :title, t("home_text") %>

<% if account_signed_in? %>
  <%= render "books_carousel", title: t(".book_top_rates"), books: @books[:top_rated_books] %>
  <%= render "books_carousel", title: t(".book_most_borrowed"), books: @books[:most_borrowed_books] %>
  <%= render "books_carousel", title: t(".book_maybe_you_like"), books: @books[:books_with_same_genre] if account_has?(:borrow_requests) %>
  <%= render "books_carousel", title: t(".book_favourite_authors"), books: @books[:books_from_favorite_authors] if account_has?(:favorite_authors) %>
<% else %>
  <div class="text-center">
    <h1><%= t "welcome_text" %></h1>
    <p><%= t "home_intro" %></p>
  </div>
<% end %>