config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "home#index"
    devise_for :accounts, controllers: {
      sessions: "accounts/sessions",
      registrations: "accounts/registrations",
      confirmations: "accounts/confirmations"
    }
    resources :accounts, only: %i(show edit update)

    resources :books, only: %i(index show), path: "library" do
      resources :book_comments, path: "comments"
    end
    resources :authors, only: %i(show)

    resource :carts, only: %i(show destroy)
    resources :borrow_items, only: %i(create destroy)
    resources :borrow_infos, only: %i(index show new create) do
      member do
        get "download", to: "borrow_infos#download"
        get "preview", to: "borrow_infos#preview"
        post "status_action", to: "borrow_infos#handle_status_action"
        patch "status_action", to: "borrow_infos#handle_status_action"
      end
    end

    resources :author_followers, only: %i(create destroy)

    resources :notifications, only: %i(index update) do
      collection do
        post "read_all", to: "notifications#read_all"
      end
    end
  end

  namespace :admin do
    scope "(:locale)", locale: /en|vi/ do
      root "home#index"
      get "export/library", to: "home#export_library"

      authenticate :admin_account do
        mount Sidekiq::Web => "/jobs"
      end

      devise_for :accounts, path: "", controllers: {
        sessions: "admin/sessions"
      }, skip: [:registrations]

      resources :authors, :genres, :publishers
      resources :books do
        member do
          get :amend, to: "books#amend_edit"
          patch :amend
        end
      end
      resources :users, only: %i(index show) do
        member do
          post :active, :inactive
        end
      end
      resources :borrows, only: %i(index show) do
        member do
          post :approve, :reject, :return, :remind
        end
        collection do
          get ":group", to: "borrows#index", as: "",
                        constraints: {group: /pending|history|borrowing/},
                        defaults: {group: :borrowing}
        end
      end
      resources :notifications, only: %i(index update) do
        collection do
          post "read_all", to: "notifications#read_all"
        end
      end
    end
  end

  namespace :api do
    scope "(:locale)", locale: /en|vi/ do
      namespace :v1 do
        post "authenticate", to: "sessions#authenticate"
        get "me", to: "sessions#me"

        post "register", to: "registrations#register"
        resources :books, only: %i(index show), path: "library" do
          resources :book_comments, only: %i(create update destroy), path: "comments"
        end

        namespace :admin do
          resources :books, only: %i(index create update show destroy) do
            member do
              patch :amend
            end
          end
        end
      end
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :borrowings, class_name: BorrowItem.name, dependent: :destroy
  has_many :books, through: :borrowings
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CartActions

  before_action :authenticate_account!
  before_action :set_cart
  before_action :check_cart_empty, only: %i(destroy)
  before_action :check_user_info

  def show; end

  def destroy
    @cart.destroy
    session[:cart_id] = nil

    flash[:success] = t "empty_cart_successfully"
    redirect_to carts_path
  end
end

app/controllers/concerns/cart_actions.rb
module CartActions
  extend ActiveSupport::Concern

  private

  def current_cart
    @current_cart ||= Cart.find_by(id: session[:cart_id])
    return if @current_cart

    @current_cart = Cart.create
    session[:cart_id] = @current_cart.id
  end

  def set_cart
    @cart = @current_cart
  end

  def check_cart_empty
    return unless @cart.borrowings.empty?

    flash[:warning] = t "no_books_in_cart"
    redirect_back(fallback_location: root_path)
  end

  def check_user_info
    return if current_account.user_info.present?

    flash[:warning] = t "borrow_info_fill_user_info"
    redirect_to edit_account_path(current_account)
  end
end

app/views/carts/_borrow_items.html.erb
<% @cart.borrowings.include_books.each do |borrow_item| %>
  <% book = borrow_item.book %>
  <tr>
    <th scope="row">
      <div class="d-flex align-items-center">
        <%= image_tag book.image if book.image.attached? %>
        <div class="flex-column ms-4">
          <p class="mb-2"><%= book.title %></p>
          <p class="mb-0 text-secondary"><%= book.authors.map(&:name).join(", ") %></p>
        </div>
      </div>
    </th>
    <td class="align-middle">
      <span><%= book.publisher.name %></span>
    </td>
    <td class="align-middle">
      <span class="text-secondary"><%= borrow_item.quantity %></span>
    </td>
    <td class="align-middle">
      <%= link_to borrow_item_path(borrow_item), data: { "turbo-method": :delete, turbo_confirm: t("you_sure?") }, class: "btn btn-primary btn-sm" do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </td>
  </tr>
<% end%>

app/views/carts/show.html.erb
<% provide(:title, t("cart")) %>

<div class="h-100 h-custom">
  <div class="container h-100 pb-5">
    <div class="d-flex justify-content-between align-items-center mb-2">
      <h2><%= t "cart" %> - <%= borrow_item_quantity %> <%= t "book" %></h2>
      <%= link_to t("empty_cart"), carts_path, data: { "turbo-method": :delete, turbo_confirm: t("you_sure?") }, class: "btn btn-primary" %>
    </div>
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col">
        <div class="table-responsive">
          <table class="table">
            <% if @cart.borrowings.count > 0 %>
              <thead>
                <tr>
                  <th scope="col"><%= t "book" %></th>
                  <th scope="col"><%= t "publisher" %></th>
                  <th scope="col"><%= t "quantity" %></th>
                  <th scope="col"><%= t "function" %></th>
                </tr>
              </thead>
              <tbody>
                  <%= render "carts/borrow_items" %>
              </tbody>
            <% else %>
              <%= render "shared/not_found_content", text: t(".cart_empty") %>
            <% end %>
          </table>
        </div>
        <div class="d-flex justify-content-end">
          <%= link_to t(".cart_add_borrow_info"), new_borrow_info_path, class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    </div>
  </div>
</div>